name: Debug Planet Order

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          python -m playwright install --with-deps chromium

      - name: Click IMAX showing
        run: |
          python debug_order.py
